- type: entity
  abstract: true
  parent: BaseGameRule
  id: BaseRandomShuttleRule
  components:
  - type: StationEvent
    weight: 10
    reoccurrenceDelay: 30
    duration: 1
    maxOccurrences: 2 # should be the same as [copies] in ship_spawns.yml
  - type: RuleGrids
  - type: LoadMapRule

- type: entity
  id: MonoMonolithicEventsScheduler
  parent: BaseGameRule
  components:
  - type: BasicStationEventScheduler
    scheduledGameRules: !type:NestedSelector
      tableId: MonoMonolithicEventsTable
    minimumTimeUntilFirstEvent: 600 # 10 minutes
    minMaxEventTiming:
      min: 420 # 7 minutes between events
      max: 1200 # 20 minutes between events